project_id = "xrlczmzgxlmdavhbwsah"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.public-task-files]
    verify_jwt = false
  [functions.email-digest]
    verify_jwt = false
  [functions.signup-email-otp]
    verify_jwt = false
  [functions.password-reset-otp]
    verify_jwt = false
  [functions.gmail-callback]
    verify_jwt = false
  [functions.payment-confirmation-email]
    verify_jwt = false
