// Lightweight hand-crafted Lottie JSON – empty box illustration
export const emptyBoxAnimation = {
  v: "5.7.4",
  fr: 30,
  ip: 0,
  op: 60,
  w: 120,
  h: 120,
  nm: "empty-box",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "box",
      sr: 1,
      ks: {
        o: { a: 1, k: [{ t: 0, s: [0] }, { t: 15, s: [100] }] },
        p: { a: 0, k: [60, 65, 0] },
        s: { a: 1, k: [{ t: 0, s: [80, 80, 100] }, { t: 20, s: [100, 100, 100] }] },
        r: { a: 0, k: 0 },
        a: { a: 0, k: [0, 0, 0] },
      },
      shapes: [
        {
          ty: "rc",
          d: 1,
          s: { a: 0, k: [50, 40] },
          p: { a: 0, k: [0, 5] },
          r: { a: 0, k: 4 },
          nm: "body",
        },
        {
          ty: "rc",
          d: 1,
          s: { a: 0, k: [56, 8] },
          p: { a: 0, k: [0, -18] },
          r: { a: 0, k: 3 },
          nm: "lid",
        },
        {
          ty: "st",
          c: { a: 0, k: [0.6, 0.6, 0.65, 1] },
          o: { a: 0, k: 100 },
          w: { a: 0, k: 2.5 },
          lc: 2,
          lj: 2,
        },
        {
          ty: "fl",
          c: { a: 0, k: [0.92, 0.92, 0.93, 1] },
          o: { a: 0, k: 100 },
          r: 1,
        },
      ],
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: "question",
      sr: 1,
      ks: {
        o: { a: 1, k: [{ t: 20, s: [0] }, { t: 35, s: [100] }] },
        p: { a: 1, k: [{ t: 20, s: [60, 40, 0] }, { t: 40, s: [60, 35, 0] }] },
        s: { a: 1, k: [{ t: 20, s: [0, 0, 100] }, { t: 40, s: [100, 100, 100] }] },
        r: { a: 0, k: 0 },
        a: { a: 0, k: [0, 0, 0] },
      },
      shapes: [
        {
          ty: "el",
          d: 1,
          s: { a: 0, k: [6, 6] },
          p: { a: 0, k: [0, 0] },
          nm: "dot",
        },
        {
          ty: "fl",
          c: { a: 0, k: [0.65, 0.65, 0.7, 1] },
          o: { a: 0, k: 100 },
          r: 1,
        },
      ],
    },
  ],
};
