import { useState, useEffect, lazy, Suspense } from "react";
import { useNavigate } from "react-router-dom";
import { useProjectPages, useCreatePage, useDeletePage, useUpdatePage } from "@/hooks/useProjectPages";
import CanvasEditor from "./CanvasEditor";
import CanvasSidebar from "./CanvasSidebar";
import { Loader2, FileText, RefreshCw, Plus, PanelLeft, Pencil, Eye, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import type { PartialBlock } from "@blocknote/core";
import { useIsMobile } from "@/hooks/use-mobile";
import type { Json } from "@/integrations/supabase/types";

const SaveAsTemplateDialog = lazy(() => import("./SaveAsTemplateDialog"));

interface CanvasPageViewProps {
  groupId: string;
  editable?: boolean;
  projectSlug?: string;
  initialPageSlug?: string;
}

export default function CanvasPageView({ groupId, editable = false, projectSlug, initialPageSlug }: CanvasPageViewProps) {
  const { data: pages, isLoading, error, refetch } = useProjectPages(groupId);
  const { user } = useAuth();
  const navigate = useNavigate();
  const createPage = useCreatePage();
  const deletePage = useDeletePage();
  const updatePage = useUpdatePage();
  const isMobile = useIsMobile();
  const [activePageId, setActivePageId] = useState<string | null>(null);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [isEditMode, setIsEditMode] = useState(editable);

  // Default sidebar closed on mobile
  useEffect(() => {
    setSidebarOpen(!isMobile);
  }, [isMobile]);

  // Resolve initialPageSlug to activePageId, or auto-select first page
  useEffect(() => {
    if (!pages?.length) {
      setActivePageId(null);
      return;
    }
    const ids = pages.map((p) => p.id);

    // If we have a slug from the URL, find the matching page
    if (initialPageSlug) {
      const matchedPage = pages.find((p) => p.slug === initialPageSlug);
      if (matchedPage) {
        setActivePageId(matchedPage.id);
        return;
      }
    }

    // If no slug or no match, auto-select first page and update URL
    if (!activePageId || !ids.includes(activePageId)) {
      const firstPage = pages[0];
      setActivePageId(firstPage.id);
      // Navigate to the first page's slug if we have projectSlug
      if (projectSlug && firstPage.slug && !initialPageSlug) {
        navigate(`/p/${projectSlug}/page/${firstPage.slug}`, { replace: true });
      }
    }
  }, [pages, initialPageSlug]);

  const navigateToPage = (page: { id: string; slug?: string | null }) => {
    setActivePageId(page.id);
    if (projectSlug && page.slug) {
      navigate(`/p/${projectSlug}/page/${page.slug}`);
    }
    if (isMobile) setSidebarOpen(false);
  };

  const handleCreatePage = async () => {
    if (!user) return;
    try {
      const maxOrder = pages?.length
        ? Math.max(...pages.map((p) => p.display_order)) + 1
        : 0;
      const newPage = await createPage.mutateAsync({
        group_id: groupId,
        title: `Trang ${(pages?.length ?? 0) + 1}`,
        content: [{ type: "paragraph", content: [] }],
        created_by: user.id,
        display_order: maxOrder,
      });
      // Navigate to the new page (slug will be auto-generated by trigger)
      if (projectSlug && newPage.slug) {
        navigate(`/p/${projectSlug}/page/${newPage.slug}`);
      }
      setActivePageId(newPage.id);
      toast.success("Đã tạo trang mới!");
    } catch (err: any) {
      toast.error(err.message || "Không thể tạo trang.");
    }
  };

  const handleDeletePage = async (pageId: string) => {
    try {
      await deletePage.mutateAsync(pageId);
      toast.success("Đã xóa trang.");
    } catch (err: any) {
      toast.error(err.message || "Không thể xóa trang.");
    }
  };

  const handleRenamePage = async (pageId: string, newTitle: string) => {
    try {
      const result = await updatePage.mutateAsync({ pageId, updates: { title: newTitle } });
      // After rename, slug may change — update URL if this is the active page
      if (projectSlug && result.slug && pageId === activePageId) {
        navigate(`/p/${projectSlug}/page/${result.slug}`, { replace: true });
      }
      toast.success("Đã đổi tên trang.");
    } catch (err: any) {
      toast.error(err.message || "Không thể đổi tên trang.");
    }
  };

  const handleChangePageIcon = async (pageId: string, icon: string | null) => {
    try {
      await updatePage.mutateAsync({ pageId, updates: { icon } });
    } catch (err: any) {
      toast.error(err.message || "Không thể thay đổi icon.");
    }
  };

  const handleChangeCover = async (pageId: string, coverUrl: string | null) => {
    try {
      await updatePage.mutateAsync({ pageId, updates: { cover_url: coverUrl } });
    } catch (err: any) {
      toast.error(err.message || "Không thể thay đổi cover.");
    }
  };

  const handleReorderPages = async (orderedIds: string[]) => {
    if (!pages) return;
    try {
      await Promise.all(
        orderedIds.map((id, index) =>
          updatePage.mutateAsync({ pageId: id, updates: { display_order: index } })
        )
      );
    } catch (err: any) {
      toast.error(err.message || "Không thể sắp xếp lại trang.");
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-muted-foreground gap-3">
        <p className="text-sm">Không thể tải nội dung trang.</p>
        <Button variant="outline" size="sm" onClick={() => refetch()}>
          <RefreshCw className="mr-1.5 h-4 w-4" />
          Thử lại
        </Button>
      </div>
    );
  }

  if (!pages?.length) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-muted-foreground gap-3">
        <FileText className="h-8 w-8" />
        <p className="text-sm">Chưa có trang nào được tạo.</p>
        {editable && (
          <Button
            size="sm"
            onClick={handleCreatePage}
            disabled={createPage.isPending}
          >
            {createPage.isPending ? (
              <Loader2 className="mr-1.5 h-4 w-4 animate-spin" />
            ) : (
              <Plus className="mr-1.5 h-4 w-4" />
            )}
            Tạo trang đầu tiên
          </Button>
        )}
      </div>
    );
  }

  const activePage = pages.find((p) => p.id === activePageId) ?? pages[0];

  const initialContent = Array.isArray(activePage.content)
    ? (activePage.content as unknown as PartialBlock[])
    : undefined;

  return (
    <div className="flex border rounded-lg bg-card overflow-hidden" style={{ minHeight: 400 }}>
      {sidebarOpen && (
        <CanvasSidebar
          pages={pages.map((p) => ({ id: p.id, title: p.title, display_order: p.display_order, icon: p.icon, slug: p.slug }))}
          activePageId={activePage.id}
          onSelectPage={(pageId) => {
            const page = pages.find((p) => p.id === pageId);
            if (page) navigateToPage(page);
          }}
          onCreatePage={handleCreatePage}
          onDeletePage={handleDeletePage}
          onRenamePage={handleRenamePage}
          onReorderPages={handleReorderPages}
          onChangePageIcon={handleChangePageIcon}
          onCollapse={() => setSidebarOpen(false)}
          editable={isEditMode}
          isCreating={createPage.isPending}
        />
      )}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 px-3 py-1.5 border-b text-sm">
          {!sidebarOpen && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-6 w-6 shrink-0"
                  onClick={() => setSidebarOpen(true)}
                >
                  <PanelLeft className="h-3.5 w-3.5" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="right">Hiện sidebar</TooltipContent>
            </Tooltip>
          )}
          {activePage.icon && (
            <span className="text-sm leading-none">{activePage.icon}</span>
          )}
          <span className="text-muted-foreground truncate flex-1">{activePage.title}</span>
          {editable && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant={isEditMode ? "secondary" : "ghost"}
                  size="sm"
                  className="h-7 gap-1.5 text-xs shrink-0"
                  onClick={() => setIsEditMode((prev) => !prev)}
                >
                  {isEditMode ? (
                    <>
                      <Pencil className="h-3 w-3" />
                      Sửa
                    </>
                  ) : (
                    <>
                      <Eye className="h-3 w-3" />
                      Xem
                    </>
                  )}
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                {isEditMode ? "Chế độ chỉnh sửa" : "Chế độ xem trước"}
              </TooltipContent>
            </Tooltip>
          )}
        </div>
        <CanvasEditor
          key={activePage.id}
          initialContent={initialContent}
          editable={isEditMode}
          pageId={activePage.id}
          groupId={groupId}
          title={activePage.title}
          icon={activePage.icon}
          coverUrl={activePage.cover_url}
          onChangeTitle={(newTitle) => handleRenamePage(activePage.id, newTitle)}
          onChangeIcon={(icon) => handleChangePageIcon(activePage.id, icon)}
          onChangeCover={(coverUrl) => handleChangeCover(activePage.id, coverUrl)}
        />
      </div>
    </div>
  );
}
